### ISSUE TITLE
Design for workload resource constraints (cpu, ram) enforcement

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#106]

**Comment by dabooz** [comment]
Design document is here: https://docs.google.com/document/d/1-CDgaft261tFWc61ZpqBMMnF28f5rkyRslAiqjasZYk
currently in progress.

**Comment by dabooz** [comment]
@bmpotter first pass of design is complete. We should discuss, there is an ugly aspect of it that might need changes in the exchange (i.e. microservice registration removal from the exchange when the device gets to capacity and what is the relationship of this problem with the MS split design that you are working on).

Right now, I would size this design as 5 days. Larger than I was expecting. A large chunk of the sizing is due to the ability to support dynamic changes to the available capacity of the device (i.e. the size of the sandbox). We could decide to not support those use cases and instead require capacity changes to occur before registration. That might reduce the sizing to 3 days.

**Comment by bmpotter** [comment]
Dup of 236
