### ISSUE TITLE
`hzn userinput add/update` should verify the user input before saving it

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#1074]
For command `hzn userinput add/update` with user json, anax should verify that 
- [x] the service exists
- [x] the variables are defined in the service (only check highest version). Return a warning message if not (eg: `warning: "$VAR1" is not defined in <$service> in highest version`)
- [x] the values have correct type. Return error if type is wrong

Create a separate issue for `hzn exchange node update`: #1081

**Comment by LiilyZhang** [comment]
@dabooz @linggao 
What does `in addition to the items listed in at the top, ...` mean in 2nd (hzn exchange node update) and 3rd (hzn business addpolicy/updatepolicy) bullet?

**Comment by dabooz** [comment]
It means in addition to verifying that (a) the service exists in the exchange, (b) the variables mentioned in the add or update are defined in the service definition and (c) the values of each variable are of the correct type; the fix to this issue should also:
a) If the node is configured to use a pattern, make sure that any service mentioned in the add/update of user inputs is referenced by the pattern or is referenced by a service that is referenced by the pattern.

I deleted the part about the business policy because that's not something we want to validate, so I removed it from the description of the defect.
