### ISSUE TITLE
If the user specifies *anything* in their pattern that we do not support, publication needs to fail with a detailed error message.

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1090]
For example, if they specify a `binds` field in their `deployment_overrides` (which is not supported) they need to receive an error message that states exactly what they did that was disallowed, so they can correct this before going through registering a device and then finding out that it just mysteriously does not work as specified.
So the code for pattern publication needs to validate *everything* in the supplied pattern definition to confirm that everything specified is supported and will be acted upon appropriately by the agent when the agreement completes on the edge nodes.

**Comment by dabooz** [comment]
Binds cannot be checked at the time of pattern deployment because the legality of a bind can only be determined when running on the device. The legality of a bind has to do with whether or not the host side of the binding allows read permissions to everyone, or not. Obviously this cannot be known at pattern deployment time.

However, this issue could still be used to analyze whether the code sufficiently checks for everything that can be checked at deployment time, and if any checks are found to be missing, this issue would fix those problems.

**Comment by jiportilla** [comment]
https://github.com/open-horizon/anax/pull/1294

**Comment by jiportilla** [comment]
also see issues anax-1290, 1291, 1292 and exchange-api 241
