### ISSUE TITLE
Two usability enhancements for horizon-container

### ISSUE THREAD

**Issue by cgiroua** [open-horizon/anax#1140]
The anax-in-a-container could use two improvements with startup/restarts:
- [x] A `--restart always` to the docker runs, to ensure the container is started back up when the docker daemon resumes
- [x] And making `horizon-container restart` idempotent (maybe a flag or something for a hard restart ... aka stop/start, or just make that the default?)

Here is some additional context for this issue from Carl:
This is something I've been dealing with, and 9/10 times when someone contacts us running on the mac it's an issue with the container running state
-Every time you shut the laptop lid the container stops, it doesn't restart when you open it
 -Running `horizon-container start` fails (because the start tries to create the container
 -Running `horizon-container restart` fails (because it tries to issue a `docker stop`)
 -You need to explicitly run `horizon-container stop && horizon-container start`

**Comment by jiportilla** [comment]
idempotent - adjective:
denoting an element of a set which is unchanged in value when multiplied or otherwise operated on by itself.

**Comment by jiportilla** [comment]
working as intended:

The anax-in-a-container could use two improvements with startup/restarts:

 A --restart always to the docker runs, to ensure the container is started back up when the docker daemon resumes
 And making horizon-container restart idempotent (maybe a flag or something for a hard restart ... aka stop/start, or just make that the default?)
Here is some additional context for this issue from Carl:
This is something I've been dealing with, and 9/10 times when someone contacts us running on the mac it's an issue with the container running state
-Every time you shut the laptop lid the container stops, it doesn't restart when you open it
-Running horizon-container start fails (because the start tries to create the container
-Running horizon-container restart fails (because it tries to issue a docker stop)
-You need to explicitly run horizon-container stop && horizon-container start
