### ISSUE TITLE
Handle blockchain write failure on agbot

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#124]
Currently the egbot  just logs the error message when the blockchain write fails. In the mean time the edge device keeps setting up the workload. The agreement will get canceled by the device after AgreementTimeoutS reached.  
Can agbot retry blockchain writting or cancel the agreement right there?

**Comment by dabooz** [comment]
The agbot does retry writes already in the go-solidity layer. The only way to inform the device that the agreement is cancelled is to write to blockchain to cancel the agreement, so if the bc is not writable for some reason, then we probably can't cancel the agreement either. The AgreementTimeoutS in the device config is there for exactly this case, so that the device will cancel if there is a problem with the blockchain write. I'm not sure there is anything additional we can do in this case.

**Comment by dabooz** [comment]
By coincidence, PR 232 added code to clean up the agbot side of the agreement more quickly when this situation occurs, but as stated above, there is nothing we can do about the device. It has to discover in time that the write didnt happen. This is a fundamental part of recording agreements on a blockchain where the parties dont trust each other.
