### ISSUE TITLE
Support agbot reading new/updated policy files w/o restart

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#164]

**Comment by dabooz** [comment]
Fixed issue 202 (as part of the PR for this issue) so that I could test.
Added unarchived filters to database searches in agbot. This was missed in the agbot/api feature.
Added a small bit of code to support multiple agreement protocols in the agbot. This was needed in order to properly react to a new policy with a new agreement protocol in it.
Most of the code is in support of dynamically adding/modifying policies int he agbot.

PR: https://github.com/open-horizon/anax/pull/210

**Comment by dabooz** [comment]
Tests I executed before submitting the PR:
Unit tests in anax, of course.
In HA and non-HA scenarios, the following;

    change property value, workload priority, invalid workload signature, policy name, in agbot policy file
    rename policy file
    add policy file containing unsupported agreement protocol name
    add and delete policy file with unused device API
    delete and re-add policy file for device api that is being used
    touch policy file - i.e. no file content changes
    modify policy file so it is no longer valid json
    workload rollback

**Comment by linggao** [comment]
Built in revision 102 (arm) and 103 (x86), version 2.0.9.
