### ISSUE TITLE
Fix problems with shared/singleton container support

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#173]
I think all 3 of these problems are related:

- when both workloads sharing a container 1st come up they cycle
- the singleton container log file name has the agr id of 1 workload or the other (should have an agreement agnostic log file name)
- when an agreement of 1 of the workloads is deleted/cancelled, anax kills the shared container too, even if it is currently being used by the other workload

**Comment by dabooz** [comment]
1. The cycling occurs when the container worker didn't find the already started shared container, and later determined that it needed to get rid of the existing container because there was a conflict. The find failed because the the internal service object was slightly different due to the filesystem mapping to the /workload_config mount point. The difference was due to a bug in the code that used the current agreement id to construct the filesytem binding for the shared container, which clearly it should not do because its shared.
2. Updated the container log file name to be specific to the shared container on the filesystem and in the syslog itself.
3. Reference count the shared usages so that clean up is done correctly.
4. Updated the sync up code at anax device startup to ensure shared containers and networks are cleaned up.

**Comment by linggao** [comment]
Built into snap revision 87 (armhf) and 88(x86), version 2.0.4.

**Comment by linggao** [comment]
Built into snap revision 87 (armhf) and 88(x86), version 2.0.4.
