### ISSUE TITLE
[BUG] Agent-Install.sh idempotency issues - function create_cluster_resources()

### ISSUE THREAD

**Issue by omega2733** [open-horizon/anax#1846]
The following function create_cluster_resources() has several child functions that do not check if resources exist before trying to create them.  This results in trying to re-create objects that already exist forcing the script to fail and exit. This is due to the code looking for a return code !=0 which always results in "failed to create <resource> exiting"

The following child function works **as expected** with a proper if statement to check for resource existence: 
- create_namespace

The following child functions **do not** work as expected due to missing the if statement the above function (create_namespace) has:
- 	create_service_account
- 	create_secret
- 	create_configmap
- 	create_persistent_volume

Detailed Logs of Errors:
[create_cluster_resources-failures.txt](https://github.com/open-horizon/anax/files/4725715/create_cluster_resources-failures.txt)

**Comment by LiilyZhang** [comment]
So since the `agent-install.sh` does not support updating agent in cluster, if any of the kubernete resources exist (except for namespace), the script will exit.

For namespace, agent is allowed to be installed in a pre-created namespace. This is because in OCP cluster, people may create image registry under same namespace(ocp project) before running the agent-install.sh

@bmpotter can I get some advice for this issue?

**Comment by LiilyZhang** [comment]
Explanation from @bmpotter : if agent-install.sh failed part way thru, resolve whatever issue it was having, and then run it again. In this case if it sees that something is already done (e.g. the openhorizon-agent namespace is already created) just keep going. So if any of the resources exists, script will skip creation and continue

**Comment by LiilyZhang** [comment]
Verified. If any of the resource existed, script continues.
