### ISSUE TITLE
Write tests for anax rollback features

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#186]

**Comment by linggao** [comment]
Test cases:
1. pairing 2 x86 nodes:  use property, counterparty attributes in the policy files for the selected agbot and both nodes so that the agreement can be negotiated with the selected agbot only. Use ha attributes to pair the nodes.
2. add a higher priority workload in the agbot policy file, test workload update case, make sure both nodes get updated.
3. add a higher priority workload , bring one node down, make sure the other node does not do the workload update.
4. add a higher priority workload that does not work, make sure both nodes roll back to the lower priority workload.
5 (optional)  add a higher priority workload,   first node gets updated, second node failed to update, make sure both fall back to lower priority workload.

**Comment by linggao** [comment]
1. To setup a HA pair and have them negotiate with the same agbots:
step 1: Choose a agbot, add the following property and counterparty property in the policy files for the services.
```
  "properties": [
    {
      "name": "agbot_host",
      "value": "testha"
    }
  ],
  "counterPartyProperties": {
    "and": [
      {
        "name": "ha_device",
        "op": "=",
        "value": true
      }
    ]
  },
```
restart anax on the agbot.
```
systemctl restart snap.bluehorizon.anax.service
```
step 2: On the device side,  turn `ha_device` to `true` from anax ` /horizondevice` api
```        {
            "account": {
                "id": "$USER",
                "email": "$EMAIL"
            },
            "id": "$DEVICE_ID",
            "name": "$DEVICE_NAME",
            "token": "$DEVICE_TOKEN",
            "ha_device": true
        }
```

step 3: On the device side, add the following ha property, property and counterparty property from anax `/service/attribute` api.
```
[
    {
        "id": "property",
        "short_type": "property",
        "label": "Property",
        "publishable": true,
        "mappings": {
                "ha_device": true
        }
    },
    {
        "id": "counterpartyproperty",
        "short_type": "counterpartyproperty",
        "label": "CounterParty Property",
        "publishable": true,
        "mappings": {
            "expression": {
                "and": [
                    {"name":"agbot_host", "op":"=", "value":"testha"}
                ]
            }
        }
    },
    {
        "id": "ha",
        "short_type": "ha",
        "label": "HA Facts",
        "publishable": false,
        "mappings": {
            "partnerID": ["<device_id_of_the_other_device>"]
        }
    }
]
```

**Comment by linggao** [comment]
test case 2: 
step1: start the agbot policy file with one workload with priority 100
'''
 "workloads": [
      {
          "priority": {
              "priority_value": 100,
              "retries": 2,
              "retry_durations": 120
          },
         "deployment": "...netspeed5:v2.4...",
          ....
     }
]
'''
make sure netspeed5 verson 2.4 is started for the workload on the device side.

step 2: add a second workload with netspeed 4:v2.5, make the priority_value 99 which means it has higher priority than the previous one.
'''
 "workloads": [
      {
          "priority": {
              "priority_value": 99,
              "retries": 2,
              "retry_durations": 120
          },
         "deployment": "...netspeed5:v2.5...",
          ....
      },
      {
          "priority": {
              "priority_value": 100,
              "retries": 2,
              "retry_durations": 120
          },
         "deployment": "...netspeed5:v2.4...",
          ....
     }
]
'''
then restart anax on the agbot
On the device side, you will see the netspeed agreement gets canceled and a new agreement get formed and the workload uses netspeed5 version 2.5.   This happens one device at a time.

**Comment by linggao** [comment]
test case 3:
step 1: same as step 1 for test case 2.
step 2 : bring down anax for one device
````
systemctl stop snap.bluehorizon.anax.service
````
step 3: same as step 2 for test case 2.
Make sure that the other device does not get updated with newer version of netspeed5 for workload.

**Comment by linggao** [comment]
test case 5: (optional)
step 1: same as step 1, 2, 3 for test case 2.
step 2: watch the first device gets updated to netspeed5 v2.5 
step 3 stop docker.service on device 2, watch the second device gets updating. Start docker.service after one retry fails. 
step 3: watch both devices. make sure the workdload roll back to netspeed5 v2.4 after some time.

**Comment by linggao** [comment]
testcase 6:
step 1. The agbot has 2 workloads for netspeed policy file. One with priority 99 and the other priority 100.
```
 "workloads": [
      {
          "priority": {
              "priority_value": 99,
              "retries": 1,
              "retry_durations": 600
          },
         "deployment": "...netspeed5:v2.5...",
          ....
      },
      {
          "priority": {
              "priority_value": 100,
              "retries": 1,
              "retry_durations": 600
          },
         "deployment": "...netspeed5:v2.4...",
          ....
     }
]
```
step 2. setup one device without ha and register netspeed service. make sure netspeed5 v2.5 is used for workload.
step 3. somehow (?) stop the data ingest so that the agbot cannot get data.  what the device roll to lower priority workload netspeed 5 v2.4.
step 5. restore the data ingest and make sure the workload on the device gets upgraded to netspeed5 v2.5.

**Comment by linggao** [comment]
testcase 7:
step 1. run test case 2. Kill the new netspeed agreement as soon as it is created before the workload started by the following command.
```
curl -X DELETE http://localhost/agreement/<agreement_id>
```
Do this for 2 new agreements so that that the 3rd agreement rolls back to the netspeed5 v2.4.
step 2. On the device side, wait for 30 minutes, delete the netspeed agreement with the following command.

curl -X DELETE http://localhost/agreement/<agreement_id>
step 2. watch the new agreement gets formed and the new workload has netspeed5 v2.4.

**Comment by bmpotter** [comment]
I split out the HA test work into a separate issue (#221) because they have different priorities.
