### ISSUE TITLE
Implement a new algorithm for timing calls to the changes api

### ISSUE THREAD

**Issue by MaxMcAdam** [open-horizon/anax#1863]
**Requirement**: 
Consider halving wait time after a change occurs. Could also make the interval reset depend on the type of change found
Implement a new algorithm for how to reduce the delay between /changes calls when a change is detected. Today it drops all the way back to 10 sec (e.g. when a msg arrives from the agbot, because we expect that when 1 msg comes in, there will probably more msgs soon - cancel msg then a new agreement), perhaps we should reduce the delay depending on what the change is (some changes might not expect additional changes in the near future). Perhaps only reduce the delay by 1/2 until we get to 10 secs.

**Design**: 
1. Will add an "alert pull interval", which is (max + min)/2. So there will be 3 intervals: 
* min -- the changes-worker pulls very frequently because there are new messages definitely coming. This is the case when agreement negotiation is in progress. 
* alert -- the changes-worker pulls more frequently than max because there may be new messages coming.  It is the case when node's policy or userinput just changed, agreement canceled by user on node or by the agbot, service/policy/pattern changes that lead to agreement cancelation etc.
* max --  The pull interval is gradually increased from _min_ or _alert_ when there are no changes until this value is reached. It will stay in this level until there are relevant changes. This is the stable case.
2. The changes-worker does not decide if a change is important or not. Instead it will  send change events out. Other workers will catch and process the changes. They send proper events if the changes are relevant. The changes-working will update the pull interval according to the type of the event.

**Comment by dlarson04** [comment]
#1824

**Comment by dlarson04** [comment]
Another consideration...

If there are 2 agbots, the agent could get 2 proposals and only one of them will be pursued. However, after the protocol timeout, the agreement sent in the unused proposal will then send a cancel message for the agreement id. Currently, this also resets the poll timer but the agent will simply ignore this cancel message because it can't find the agreement id. It would be an improvement if the poll timer is reset/reduced only when there is a message that actually is used by the agent.
