### ISSUE TITLE
Remove horizon.pem and mtn-publicKey.pem from deb and RPM packages

### ISSUE THREAD

**Issue by dabooz** [open-horizon/anax#1926]
Those certs should no longer be needed, but this needs to be tested.
And, we need to make sure that e2edev still runs without them (or it's updated to run without them).

**Comment by IntelliJIN** [comment]
WIP

**Comment by bmpotter** [comment]
Note that 1 of the reasons these files were left in the `horizon` pkg was because we moved them from the `bluehorizon` pkg to `horizon`, and when they weren't in the `horizon` pkg, `apt-get install ...` didn't completely git rid of the `bluehorizon` pkg. So while you are making this change, you need to test the case it which the system has an older `bluehorizon`, `horizon`, and `horizon-cli` deb pkg installed and you upgrade to your new `horizon` and `horizon-cli` pkgs (and run dpkg -l to see what is left).

Also, the files should also be removed from the `horizon` rpm. (For the rpms you don't have the same migration issue, because there has never been a `bluehorizon` rpm.

**Comment by bmpotter** [comment]
@IntelliJIN I'm reviewing https://github.com/open-horizon/anax/pull/2037, but you never responded to my comment above, so i don't know if you addressed and tested my concern about upgrading on a system that had the `bluehorizon` deb pkg installed.

**Comment by bmpotter** [comment]
Haven't heard from @IntelliJIN in a while. We might have to take this issue over and complete the in-progress PR https://github.com/open-horizon/anax/pull/2037 .

**Comment by rajpratyush** [comment]
@bmpotter if you guide me I would like to complete the PR

**Comment by bmpotter** [comment]
@rajpratyush Yes, you can work on this! It looks like @IntelliJIN doesn't have time to complete it. Look at his [PR}(https://github.com/open-horizon/anax/pull/2037) and start from there. But notice my comment above in this issue.

**Comment by rajpratyush** [comment]
@bmpotter sure sir i am on it

**Comment by dabooz** [comment]
@rajpratyush I updated the labels on this issue to reflect that it is in progress again.
