### ISSUE TITLE
Add support for SDO to LF Edge adam/eve

### ISSUE THREAD

**Issue by dcmartin** [open-horizon/anax#1928]
Provide well-known SDO "Adam" service/API capabilities, including corresponding database of credentialed devicdes (n.b. "vouchers"), to enable automated on-boarding of devices that have corresponding credentials stored in an "Adam" service.

Provide mechanism to manage credentials for both client and "Adam" service
  + client credentials should emulate "factory-installed" credentials
  + service credentials (aka "voucher") should emulate "factory-installed" credentials
  + service should provide for standard CRUD operations on client-credentials "vouchers"

Provide mechanism to enter device into exchange as node
  + create nodes based on successful on-boarding
  + modify/delete nodes based on change-in-ownership and other SDO changes
  + utilize common PKI credentials, tokens, etc.. as appropriate

**Comment by bmpotter** [comment]
DCM, i don't understand what you are requesting. You are going to have to describe it more clearly and concretely. And describe it as deltas from what https://github.com/open-horizon/SDO-support already provides and what we are planning for our next release, which is:

- automatically set up the SDO owner services as part of the mgmt hub install
- add `hzn voucher list` sub-command
- swagger documentation for the OCS API

**Comment by bmpotter** [comment]
Also, in addition to explaining what you mean more clearly, please provide a specific/concrete proposal in this issue about what integration and/or functionality should be added. Thx.

**Comment by bmpotter** [comment]
@joewxboy please evaluate this and post a recommendation here of what should be done (if anything) and how to proceed. Thx!

**Comment by joewxboy** [comment]
When this issue was first created, SDO was not yet an official LF Edge project.  Now that it is, this ticket is more properly a collaboration between the SDO project and the EVE project.  EVE has requested that Open Horizon collaborate with them on [Adam](https://github.com/lf-edge/adam), but we have not agreed to take that on at this time.  I'd recommend closing this ticket and re-opening it in the Adam and/or SDO repos and linking the two tickets.  It's up to those two projects.
