### ISSUE TITLE
agent_install does not change the registration when hzn is not found

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#2150]
on my mac, I had an agent running with policy. I removed the cli using horizon-cli-uninstall.sh.  Then I reinstalled everything with
````
agent-install.sh -i css:  -p IBM/pattern-ibm.helloworld -w '*' -T 120 
````
However, the install succeeded without using the pattern. I saw this at the end of the install.
```
2020-10-06 22:53:49 Waiting for state: Horizon agent ready 
2020-10-06 22:53:50 Done: Horizon agent ready
2020-10-06 22:53:50 The current registration settings are correct, keeping them.
````

````
hzn node list
{
  "id": "LingMac",
  "organization": "anaxsquad",
  "pattern": "",
  "name": "LingMac",
  "nodeType": "device",
  "token_last_valid_time": "2020-10-06 21:43:54 -0400 EDT",
  "token_valid": true,
  "ha": false,
  "configstate": {
    "state": "configured",
    "last_update_time": "2020-10-06 21:43:56 -0400 EDT"
  },
  ...
  }
}
````
Then I ran the same agent install command again, the  pattern registered with the node.

**Comment by bmpotter** [comment]
This problem is not really in `agent-install.sh`, because it (rightly) assumes that if the `hzn` command is not present then the node can't be registered, because for ubuntu and rhel the `horizon-cli` is tied to the `horizon` package (so you can't remove 1 w/o removing the other). Also, `agent-install.sh` would have no way of knowing that the node is registered w/o `hzn`.

The real problem on macOS is that `horizon-cli-uninstall.sh` allows removing `hzn` w/o removing the agent (the `openhorizon/amd64_anax` container). So it should be enhanced to also stop the `openhorizon/amd64_anax` container.
