### ISSUE TITLE
hzn service list on node running a service shows an empty list

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2558]
I registered a node with a policy and the service started. However, `hzn service list` shows an empty list

```
root@plasmas1:~# hzn version
Horizon CLI version: 2.29.0-449
Horizon Agent version: 2.29.0-449
```

```
root@plasmas1:~# hzn service list
[]
```

But I can get the logs from the running service

```
root@plasmas1:~# hzn service log deploy-hellomms
Displaying log messages for service deploy-hellomms with service id d0ddf676dc4d0ff3c265beb9075b4853217fd256353f570bd51d28c7fd013740.
Jun  9 08:32:15 plasmas1 workload-d0ddf676dc4d0ff3c265beb9075b4853217fd256353f570bd51d28c7fd013740_deploy-hellomms[1385]: plasmas1.fyre.ibm.com_horizon0 says: Hello from the dockerfile!
Jun  9 08:32:20 plasmas1 workload-d0ddf676dc4d0ff3c265beb9075b4853217fd256353f570bd51d28c7fd013740_deploy-hellomms[1385]: plasmas1.fyre.ibm.com_horizon0 says: Hello from the dockerfile!

```

**Comment by linggao** [comment]
This issue will be fixed when https://github.com/open-horizon/anax/issues/2267 is fixed.

**Comment by linggao** [comment]
Currently `hzn service list` shows the output from `/service/config` APIs. It shows the services that has user input that are entered through the PUT `service/config` API. But since we are switching to use `/userinput` API, this command often shows an empty list.  Should we change this function to show the service name/org/version/arch from the microservice definitions?

**Comment by dlarson04** [comment]
verified in
root@plasmas1:~/scaler# hzn version
Horizon CLI version: 2.29.0-538
Horizon Agent version: 2.29.0-538
