### ISSUE TITLE
Panic in semanticversion/version.go

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#2792]
Error messages like this one appear in the agbot every few hours but dont appear to be causing a problem:

`Aug 30 09:32:24 ibm-edge-agbot-79f479574d-kcrq2 ibm-edge-agbot error E0830 13:32:24.702559       8 agreementworker.go:527] Base Agreement Worker (68f4b630-7eed-41ce-8e4d-33623b9d2667): error searching for service details Priority: PriorityValue: 0, Retries: 0, RetryDurationS: 0, VerifiedDurationS: 0, Deployment: , DeploymentSignature: , DeploymentUserInfo: , Workload Password: , ClusterDeployment: , ClusterDeploymentSignature: , Workload URL: ibm.cpu2evtstreams, Org: IBM, Version: 1.4.3, Arch: amd64, Deployment Overrides: , Deployment Overrides Signature: , error: unable to create version expression from , error Version_Expression: (2792c) Empty string is not a valid version`

The agbot fails the agreement attempt and later retries, causing longer agreement times than necessary, but that's the only symptom experienced by the user.

**Comment by dabooz** [comment]
The problem occurred because the service def cache was caching service defs with an empty version field in the requiredServices array. Some time ago, the version field of the requiredServices array was changed from version to versionRange to more accurately reflect the meaning of that field. Since all the code was built on the version field, some backward compat code was added to copy the versionRange field into the version field, if version was empty. The service def was cahced before this backward compat code was called resulting in the empty version string error messages.
