### ISSUE TITLE
Literal service version number with leading zero fails in agreement formation 

### ISSUE THREAD

**Issue by SanjeevKGupta** [open-horizon/anax#2829]
If service version in deployment policy.has leading zeros such as `27.07.02` it fails to form an agreement for a service published with  `27.07.02` . 

Looks like service version in deployment policy and service.definition.json have to be group of integers without leading zeros. Looks to be a case of string vs integer. 

Docker images are(can be) published as 27.07.02 which is not same as 27.7.2

**Comment by dabooz** [comment]
Unit tests for the semantic version package don't test for this case. Should be easy to add some tests and fix the code.

**Comment by rohan-kulkarni-25** [comment]
Hey If this is not yet resolved will like to fix it @dabooz @LiilyZhang

**Comment by Polber** [comment]
Hi @rohan-kulkarni-25, it should be assigned to you now.

**Comment by rohan-kulkarni-25** [comment]
> Hi @rohan-kulkarni-25, it should be assigned to you now.

Ok !! Thanks will come up with a PR !! Will you please guide how to start.

**Comment by dabooz** [comment]
@rohan-kulkarni-25 Welcome and thanks for picking up the issue. We have some guidelines for PRs, which probably aren't as clearly documented as they should be:
1) The PR should have only 1 commit in it when you submit for review. You can commit as often as you want in your Git workspace, but you will need to squash them all to 1 before you submit for review.
2) The commit message should be in the form: "Issue xxxx - some short description"
3) Don't forget to commit with the -s flag to digitally sign your PR as your original work.
Items 1 and 2 are necessary because the build process automatically produces a change log that goes into the final packages, and it uses commit message to indicate each change, this the need for 1 commit per PR and a standard message format.
Please feel free to reach out for help to the Agent workgroup in the LF Edge IM system.

**Comment by linggao** [comment]
Verified.
