### ISSUE TITLE
Anax support user specified device id and token

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#324]
Allow user to specify device id when calling POST /horizondevice, but it is only allowed to post once.

**Comment by linggao** [comment]
PR https://github.com/open-horizon/anax/pull/325

**Comment by bmpotter** [comment]
Ling, i need more detail about exactly what you supported for this. Here are my needs (a couple of these are new, based on what we are learning about wiotp scenarios):

1. At registration time, optionally accept from the user a device id and device token. If specified, these values should both be set in the exchange and in `POST /horizondevice`.
    - if device id isn't specified, it should default like it does now (e.g. the rpi serial number)
    - if the device token isn't specified, it should be auto-generated like it does now
1. If the device already exists in the exchange (and its token is the same as what they specified), the user doesn't need to give you a user/pw (horizon will just update the existing exchange device resource, using the device id/token as credentials). This is important because wiotp's concept of users is different from the exchange's, so we won't be sync'ing users from wiotp to exchange.
1. (Maybe post-MVP1) Support the scenario in which a 3rd party vendor wants to completely configure a specific device for the customer. This means:
    - Ahead of time they install the device with ubuntu or raspian, and install the bluehorizon deb pkg
    - They put the customers device id and token in a particular dir/file (along with any other variables needed for registration) - this would be similar to the env_vars file that we have today.
    - When the customer gets the device and boots it up, horizon starts and recognizes that file, and automatically registers (w/o user intervention).

**Comment by bmpotter** [comment]
About #1 above: anax api supports passing in both now. Reg_all supports setting both in env_vars. Reg UI needs to do the same.

**Comment by linggao** [comment]
Need more work on #2.
Opened Issue 333 for #3

**Comment by linggao** [comment]
For #2 check if we need account id in Horizon device. Try to remove it in anax.
In reg_all and gui registration, accept cases where only  device id/token are specified (without user/password).  So user can specify either user/password or device id/token or both.
