### ISSUE TITLE
DELETED: Unconfig node command hung if issued right after configstate call

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#401]
start anax
run reg_all
run `curl -X DELETE http://localhost/horizondevice` right after the reg_all call.
The last command hang for a very very long time.
The agreements stayed on the agbot for a long time.

if run `curl -X DELETE http://localhost/horizondevice?removeNode=true` immediately after running reg_all, the command returned. The node was removed from the exchange. New anax started.
But the agreements stayed on the agbot for a long time.

**Comment by dabooz** [comment]
I need more info. Do you have a log file or more details?

**Comment by dabooz** [comment]
@linggao I have done ALOT of testing on this in the last few days using a scenario like you describe and I have not encountered the problem you describe. The only problem I saw was #405 which seems to be different from you describe. In issue 405 anax terminates with a panic so the DELETE command never completes, the client's socket ends when anax dies. You need to recreate this and capture the log file, otherwise there's nothing else I can do.
