### ISSUE TITLE
GPS sample service improvements

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#451]
- [x] Change gps such that if there is no gps sensor and lat/lon env vars don't have a meaningful value (0, 0) or blank, default to get lat/lon via ip address
- [x] Change the location workload such that it can either send data to bluehorizon.network or witop (if HZN_DEVICE_ID is the form g@gwtype@gw)
- [x] Change the Dockerfile FROM statements to refer to a publicly available image (for all arch's)
- [x] Move to github.com/open-horizon/examples
- [x] Make the gps and location examples so they are immediately usable in the `hzn dev` environment (either gps used by a workload the developer is creating, or where he is starting from gps and location and modifying them). You can look at cpu_percent/cpu2wiotp as examples of this.

**Comment by TheMosquito** [comment]
The "private-data" microservice (which Egan requested me to write way back to encapsulate all the PII data, including location, but which was later cancelled before deployment) contains the code to get the public IP address of a machine NATted behind a firewall. Specifically, this code is in `wave/edge/firmware/private_data/src/hpd/hpd.go`) and the function that does the work is copied below:
```// Return the public Internet IP address (using http://ifconfig.co)
func get_public_address() (ip_address string) {
        // Using https sometimes fails with a 509 due to certificate errors
        resp, err := http.Get("http://ifconfig.co")
        if err != nil {
                return fmt.Sprintf("Error from ifconfig.co: %v", err)
        }
        defer resp.Body.Close()
        body, err := ioutil.ReadAll(resp.Body)
        ip_address = string(body[:len(body)-1])
        return
}
```
Regarding `"privileged":false` for gps, I tested the following (with no wildcard, and no `--privileged` but explicitly specifying `--device /dev/bus/usb/001/001 --device /dev/ttyACM0 --device /dev/ttyAMA0`):
```root@horizon-00000000660d9963:~/wave/edge/firmware/gps# docker stop gps; docker rm gps
gps
gps
root@horizon-00000000660d9963:~/wave/edge/firmware/gps# docker run -d --device /dev/bus/usb/001/001 --device /dev/ttyACM0 --device /dev/ttyAMA0 -e HZN_GPS_PORT=31779 -e HZN_USE_GPS=true -e HZN_USER_PROVIDED_COORDS=false -e HZN_LAT=37.0 -e HZN_LON=-121.0 -e HZN_LOCATION_ACCURACY_KM=10.0 --net=gps-test --net-alias=gps --name gps summit.hovitos.engineering/arm/gps:2.0.3
e96e70fac746fc18b3b8ea1bdf72584a13c673f988b0c9741fb54e638d40f961
root@horizon-00000000660d9963:~/wave/edge/firmware/gps# docker inspect gps | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "",
                    "IPAddress": "172.18.0.2",
root@horizon-00000000660d9963:~/wave/edge/firmware/gps# curl -sS -w "%{http_code}" http://172.18.0.2:31779/v1/gps/location | jq .
{
  "latitude": 37.273269167,
  "longitude": -121.881160833,
  "elevation": 37.7,
  "accuracy_km": 0,
  "loc_source": "GPS",
  "loc_last_update": 1517350315
}
200
root@horizon-00000000660d9963:~/wave/edge/firmware/gps#
```
The `--device /dev/ttyAMA0` entry hasn't been passed in production for some time (but used to be).  Maybe since we have had `--privileged` in prod for a long time that may have made it not required.  So I think it is probably safest to keep that when you remove `--privileged`.  If you remove it, I know that the GPS units that Bruce and I have will still work and any other GPS units coming in on usb 1/1 should still work too (although I have no way to test the latter).
