### ISSUE TITLE
Anax handle unregister when when org has disappeared

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#490]
The context: i was testing setting up my dev2 edge node in the wiotp test environment. The setup went perfectly (got the node registered, agreements made, iot-core workload running). But the wiotp periodically resets their test env, wiping orgs, etc, and that happened last night. So this morning in the test env cloud ui i created a new org, device, etc, and wanted to reconfigure my node to use that.

But `hzn unregister` failed because the org it was currently register for no longer existed. Hzn got an non-nil err from `httpClient.Do(req)` that contained "Delete http://localhost:8081/node?block=true: EOF". It left the node in the `unconfiguring` state, the agreement was still active, and the containers were still running. So basically it didn't get very far in unregistering. Since it is in the `unconfiguring` state, i can't do much else with the node.

The wiotp team said they have seen this (i think it is consistently re-creatable) and the only way they know to get out of it is uninstall horizon and reinstall. (I'm sure i could probably stop the service and delete the db, but reinstalling is easier.) So i'm going to do that so i can move forward. We can recreate if you need it to debug.

**Comment by linggao** [comment]
I cannot recreate the problem with the latest code. I did `hzn registration`, then removed the org that the pattern is in. The edge node automatically got the agreement canceled and the node unregistered. I could start another registration without problem. I did not have to run `hzn unregister` because it was in the unconfigured state after the pattern org (hence the node org) was deleted.

**Comment by linggao** [comment]
I tried just delete the node from the org only, the agreement was still running. Then I ran `hzn unregister`, it went to successfully.
