### ISSUE TITLE
agbot policy manager failed initializing when there are 2 policies with the same name

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#557]
When agbot starts, the policy manager failed to initializing.
This is because both both public/netspeed-amd64.policy and public/pws-amd64.policy have  
```    
"header": {
        "name": "netspeed_amd64",
        "version": "2.0"
    },
```

The policy manager is using the name as the key. So it detected 105 files but only got 104 policies. So policy managed failed to initialize. Hence the agbot no longer negotiated with the nodes for agreements.

Should policy manager fail like it is doing now or keep working in this situation? If it keeps working, shall we pick one of the above policies (first come first serve) or reject both?

**Comment by dabooz** [comment]
The policy name is the thing that uniquely identifies the policy, and that was by design. I think the agbot should keep working, there is no reason to penalize the policies that are working correctly by having the agbot be down just because one of the policies has a mistake in it. I think there should be an error in the log. I think we need a way for that error msg to be surfaced outside the log into some kind of monitoring tool so that someone can take action to correct the situation.
