### ISSUE TITLE
Policy for allowing privileged and --network=host services

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#884]
In order to mitigate security risks to containers running on the same device (node), the following design is proposed:
a) Invent a new R/W builtin node property called openhorizon.allowPrivileged which is a boolean type, the default is false. Currently all builtin properties are R/O, a builtin that is R/W is something new.
b) Service definitions are introspected (recursively) for the use of either privileged or network==host. If one or both are found, the service is designated to have the builtin property openhorizon.allowPrivileged=true. That is, even when service A (with no direct privileged usage) depends on service B (which does have direct privileged usage), then service A is designated as using privileged capability, resulting in openhorizon.allowPrivileged=true implicitly set on A.
c) Nodes that want to allow privileged services MUST set openhorizon.allowPrivileged=true.
d) Business policies, by default, have openhorizon.allowPrivileged==false implicitly present (built in) in their constraint expression, except when the policy refers to a service (even recursively) that has openhorizon.allowPrivileged=true.
e) A business policy constraint can explicitly specify openhorizon.allowPrivileged==true or false, but it is an error to specify false when service introspection indicates privileged capability is in use.
f) A service can explicitly specify the property openhorizon.allowPrivileged=true or false, but it is an error to specify false when service introspection indicates privileged capability is in use.
g) A pattern that refers to (even recursively) a service which has privileged usage, can only be deployed to a node that has openhorizon.allowPrivileged=true.
h) Support network=host in the deployment configuration for a container.
i) A business policy can set openhorizon.allowPrivileged=true OR openhorizon.allowPrivileged=false in a constraint expression to allow a service to be deployed to both kinds of nodes.

The net of this design is that any node which sets openhorizon.allowPrivileged=true will only have services deployed to it which use either privileged or network=host. And the corollary, any service which uses either privileged or network=host will not be deployed to any nodes by default. While this is an incompatible change, it is the safe change based on security considerations. Further, this design means that services which don't exploit privileged or network=host, but that are willing to be deployed with services that do use these capabilities, can override the default behavior in a business policy or pattern.

**Comment by dabooz** [comment]
In order to mitigate security risks to containers running on the same device (node), the following design is proposed:
a) Invent a new R/W builtin node property called openhorizon.allowPrivileged which is a boolean type, the default is false. Currently all builtin properties are R/O.
b) Service definitions are introspected (recursively) for the use of either privileged or network==host. If one or both are found, the service is designated to have the builtin property openhorizon.allowPrivileged=true. That is, even when service A (with no direct privileged usage) depends on service B (which does have direct privileged usage), then service A is designated as using privileged capability, resulting in openhorizon.allowPrivileged=true implicitly set on A.
c) Nodes that want to allow privileged services MUST set openhorizon.allowPrivileged=true.
d) Business policies, by default, have openhorizon.allowPrivileged==false implicitly present (built in) in their constraint expression, except when the policy refers to a service (even recursively) that has openhorizon.allowPrivileged=true.
e) A business policy constraint can explicitly specify openhorizon.allowPrivileged==true or false, but it is an error to set false when service introspection indicates privileged capability is in use.
f) A service can explicitly specify the property openhorizon.allowPrivileged=true or false, but it is an error to specify false when introspection indicates privileged capability is in use.
g) A pattern that refers to (even recursively) a service which has privileged usage, can only be deployed to a node that has openhorizon.allowPrivileged=true.
h) Support network=host in the deployment configuration for a container.

The net of this design is that any node which sets openhorizon.allowPrivileged=true will only have services deployed to it which use either privileged or network=host. And the corollary, any service which uses either privileged or network=host will not be deployed to any nodes by default. While this is an incompatible change, it is the safe change based on security considerations. Further, this design means that services which don't exploit privileged or network=host, but that are willing to be deployed with services that do use these capabilities, can override the default behavior in a business policy or pattern.
