### ISSUE TITLE
Improve error message in hzn dev service start

### ISSUE THREAD

**Issue by edgedock** [open-horizon/anax#889]
Saw this message when executing...
hzn dev service start -f horizon/userinput.json

Error: 'service start' unable to start file sync service, unable to start mongo DB for CSS, error unable to create mongo DB container, error container already exists.

Chaining four error messages was confusing to me when I first saw that. Looking from user’s perspective, following the error message if we can also add as to what action should user take, that would be helpful. 

Created this issue on Ling's suggestion.

**Comment by bmpotter** [comment]
The sync service will have the option to run with a built-in db (bolt db, the same one the horizon agent uses). When `hzn dev service start` starts css, it will always use this option, because that’s the right option for a local dev environment. This is explained in https://github.com/open-horizon/anax/issues/814 . At that point, this whole issue will go away, so i'm closing this issue.
