### ISSUE TITLE
Add flag to 'hzn exchange service publish' to get docker image digest by pulling

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#967]
Normally `hzn exchange service publish` gets the docker image digest by pushing the docker image to the registry (and then changes the `image` in the service def accordingly). But when priming the ICP exchange we need to publish service defs w/o building/pushing the docker images. So add a flag `P` that will cause it to pull the docker image instead (this is the only other way to get the docker image).

- The flag -P is mutually exclusive with -I.
- The description of the flag `-P: Use the image from the image repository. It will pull the image from the image repository and overwrite the local image if exists. This flag is mutually exclusive with -I. `
- Pull the image, get the digest, rewrite the `image` field, then PUT the definition to the exchange like normal. If the image is not already in the docker registry, it is an error (when this new flag is used). The only logic change is: if `-P` specified, docker pull instead of docker push. Everything else stays the same.

Needed by https://github.com/open-horizon/examples/issues/190

**Comment by TheMosquito** [comment]
In case it is helpful, here is some info about getting a Docker container image's sha256 hash:
```root@glendarling0:~/foo# docker image inspect ibmosquito/myhello_amd64:1.0.0 | jq '.[].RepoDigests'
Error: No such image: ibmosquito/myhello_amd64:1.0.0
root@glendarling0:~/foo# docker pull ibmosquito/myhello_amd64:1.0.0
1.0.0: Pulling from ibmosquito/myhello_amd64
bdf0201b3a05: Pull complete 
Digest: sha256:a560bf389679a9217dc0e36b7b16198b83998c0a92a19784e61a949f5b1a97ce
Status: Downloaded newer image for ibmosquito/myhello_amd64:1.0.0
root@glendarling0:~/foo# docker image inspect ibmosquito/myhello_amd64:1.0.0 | jq '.[].RepoDigests'
[
  "ibmosquito/myhello_amd64@sha256:a560bf389679a9217dc0e36b7b16198b83998c0a92a19784e61a949f5b1a97ce"
]
root@glendarling0:~/foo#``` 
That is, `docker image inspect` will give it to you.
Sorry, forgot to share this after the meeting this morning. (edited) 
From the above (which I did weeks ago and saved) it looks like you need to actually pull the image locally in order to get the hash, in general.
For dockerhub, you can use https://microbadger.com/ to get it without a pull.
microbadger.com
MicroBadger
What's inside your Docker containers? Inspect labels, layers and other metadata.
But IDK how to use that on other private container services which we also support (like IBM Container Registry).
