### ISSUE TITLE
'too many open files' error in syslog

### ISSUE THREAD

**Issue by linggao** [open-horizon/anax#969]
When the node cannot connect to the exchange or cannot check docker containers due to 'too many open file', we found that there are over 1000 file descriptor for anax using `lsof |grep anax`. Most of them are like  this:
````
anax      30626 30630       root  284u     IPv4          125576247      0t0        TCP lingvs1.dev.edge-fabric.com:58032->6e.1f.2ea9.ip4.static.sl-reverse.com:https (CLOSE_WAIT)
````
There might be a leak of file descriptors somewhere.

**Comment by dabooz** [comment]
I have been trying different things to recreate anything even close to the reported symptoms but have been unable to do so. Not ready to close it just yet.

**Comment by dabooz** [comment]
Still cannot recreate this. This occurred once to a user who was experiencing a problem connecting to the CSS component (the CSS ingress was down on the cloud side). This lead to a secondary problem where the embedded ESS would not terminate itself (because it could not connect to the CSS). The ESS termination code was fixed to allow for termination and eventually the CSS ingress was also fixed. As part of the ESS fix, http client handling was changed. It's possible that this why it is no longer possible to recreate anything close to the original problem.
